// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import { DarkModeToggle } from "@/components/dark_mode_toggle";
import Footer from "@/components/footer";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "MemoTag",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="[font-family:sans-serif] antialiased relative">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Navbar />
          <main className="min-h-screen overflow-y-scroll">
            {children}
          </main>
          <Footer />
          <DarkModeToggle />
        </ThemeProvider>
      </body>
    </html>
  );
}
